version: "3.9"

services:

  database:
    container_name: database
    image: postgres:14.2-alpine3.15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - 'database'

  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - 'database'
